<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AiDevs4</RootNamespace>
    <UserSecretsId>b3f7a2e1-5d8c-4f6a-9e1b-2c3d4e5f6a7b</UserSecretsId>
    <AnalysisModeStyle>All</AnalysisModeStyle>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <!--   Trimming     -->
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <PublishTrimmed>false</PublishTrimmed>
    <!-- <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator> -->
    <TrimMode>partial</TrimMode>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.AI.Inference" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Ollama" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

</Project>
