<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Aspire AI Client Packages -->
    <PackageVersion Include="Aspire.Azure.AI.Inference" Version="13.1.1-preview.1.26105.8" />
    <PackageVersion Include="Aspire.OpenAI" Version="9.1.0-preview.1.25121.10" />
    <PackageVersion Include="CommunityToolkit.Aspire.OllamaSharp" Version="9.1.0" />
    <!-- Core AI packages -->
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.260209.1" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.260209.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.AI" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.AI.Ollama" Version="9.7.0-preview.1.25356.2" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.2" />
  </ItemGroup>
</Project>
